### ISSUE TITLE
Qoutes with println

### ISSUE THREAD

**Issue by shakna-israel** [orangeduck/Cello#103]
I'm probably doing something stupid, but I can't quite work out what.

I have a function that returns a random Cello String from a group, using a case switch and a random number generator.

```
return $S("Troll");
```

The function I'm working on uses that random adjective to print to the console...

```
var adjective = get_adjective();
println("You encounter a %$!", adjective);
```

Unfortunately, it prints out like:

```
You encounter a "Troll"!
```

Whereas, what I'm aiming for is:

```
You encounter a Troll!
```

I'm not sure what I'm missing here, I thought println took Cello Types, and $I(10) and the like print without these quotes, so I'm guessing its unique to strings... Am I meant to cast them, or something?

**Comment by orangeduck** [comment]
Hi,

The simplist way to do what you want to achieve is to just use the format specifier `%s` instead of `%$`. The `%s` format specifier acts like the normal C format specifier but where any object that implements the [`c_str`](http://libcello.org/learn/c_str) class can used with it. So it will print the string without quotes. The `%$` format specifier is more like printing an object in a representation it can be reconstructed from. The difference between these two is like the difference between `__repr__` and `__str__` in Python if you are familiar with that.

Also if you are returning an object from a function you better allocate it on the heap instead of the stack - see [this article](http://libcello.org/learn/queries-and-pitfalls#returning-stack-objects).

Hope that helps!

- Dan

**Comment by shakna-israel** [comment]
That makes total sense. Thanks. (And I've made sure to allocate, just trying to break the example down).
