### ISSUE TITLE
Problematic Map_Put() / Map_Get()

### ISSUE THREAD

**Issue by zhangchn** [orangeduck/Cello#81]
It is implied from `Map_Get()` that the tree in `md->root` should at the very least be a Binary Search Tree. However the `Map_Put()` does not seem to respect the restriction that after inserting a new node, the key of any node is greater than any key from left subtree and less than any from right subtree.

And it seems that the `Map_Put()` would easily lead to degeneration of the tree into a linked list, after a few times of insertions.

**Comment by orangeduck** [comment]
Yes currently the Map data structure doesn't self balance. Sorry this is an improvement that really needs to be made which I've not found time to add as I've been very busy at my main job.

The good news is that I'm actually currently in the middle of a large revamp of Cello, which includes improving all of the data structures to remove the obvious problems like these and try to make them state-of-the-art. If you can wait a few months this may be ready then, otherwise I welcome pull requests.

Thanks

**Comment by zhangchn** [comment]
The problem is not really about balancing. It is about that binary search on the tree may fail when it should not.

**Comment by orangeduck** [comment]
Do you have an example of it failing I could use to debug?

**Comment by zhangchn** [comment]
I have tried to replace Map's implementation using BSD API `rb_tree_*`.
Even after that I still got absurd exceptions in `Map_Get()`, and it turned out that something was seriously wrong in `String_Lt()`.

In my case, `String_Lt()` tells `rb_tree_find_node()` that `$(String, "od")` < `$(String, "oed")`, and that  `$(String, "od")` < `$(String, "oed")`, etc.!

After replacing the comparison in `String_Lt()` with `strncmp() < 0 ? True : False`, it went smoothly.

**Comment by orangeduck** [comment]
Thanks for checking this out. Don't know why I tried to write my own broken implementation of comparing strings. Must have been a moment of insanity! I'll fix that and just use `strncmp` instead.

**Comment by zhangchn** [comment]
It seems my naive rb_tree implementation for Map works but it does break a test case, where the order of keys are required.

**Comment by orangeduck** [comment]
Actually I think that test case is wrong along with the implementation - and that the new string comparison function is right. I changed it in the latests commits.
