### ISSUE TITLE
Cannot compile in cygwin due to missing header file.

### ISSUE THREAD

**Issue by polyglotCipher** [orangeduck/Cello#85]
Cygwin's gnulib does not provide execinfo.h, possibly due to compatibility issues with the underlying (Windows) system. I believe this includes the implementation of backtrace as a whole.

    
    $ make
    mkdir -p obj
    cc src/Array.c -c -I ./include -std=gnu99 -Wall -Wno-unused -fPIC -o obj/Array.o
    src/Array.c:1:0: warning: -fPIC ignored for target (all code is position independent)
     #include "Cello.h"
     ^
    In file included from src/Array.c:1:0:
    ./include/Cello.h:127:22: fatal error: execinfo.h: No such file or directory
     #include <execinfo.h>
                          ^
    compilation terminated.
    Makefile:78: recipe for target 'obj/Array.o' failed
    make: *** [obj/Array.o] Error 1

**Comment by orangeduck** [comment]
Thanks for the report. Sorry I don't have much experience with Cygwin, but does this mean it doesn't define `_WIN32` but it does define `__unix__`? That is kind of odd. Looks like I might need a proper configure script to test for the inclusion of these headers.

For now if you want a quick hack to get started you can just do `#define CELLO_NSTRACE` at the beginning of the header.

**Comment by polyglotCipher** [comment]
I managed to compile it and get it working.
Here is what I had to do:
 - As you said add `#define CELLO_NSTRACE` to the Cello header file.
 - When testing `ifeq ($(findstring MINGW,$(PLATFORM)),MINGW)` in the makefile if I remove the `-rdynamic` flag in the `else` section which is needed when using `backtrace()` (which cygwin doesn't support hence the missing `execinfo.h` header) then the compilation works. I suggest having a test case in the makefile for cygwin that doesn't enable that flag.
 - When I compiled one of the examples using the dynamic library I noticed that the `-l` option can't find `.so` libraries so I renamed it to a `.dll` but then when the executable is run the program looks for an `.so` file so in order to both compile and run the program I had to either make a sym link to the `.so` file with a `.dll` suffix (or visa versa) or rename it (the library) after compilation. I don't if this is something that is fixable, it still works, but I just wanted to put it in here in for reference.

Thanks for you help; I love the library!
(I like the new website, too, by the way.)

**Comment by orangeduck** [comment]
Hey,

Perhaps you can see if this is fixed in 5d9ac93841ae1ec25d088e67e5e4db8c28e5e231. I updated the makefile to look for the stacktrace stuff conditionally.

I installed 64 bit Cygwin to test this and it was acting like MinGW (I.E it defined `_WIN32` not `__unix__` and was wanting to compile using `DbgHelp`). So in the Makefile I've set it up to think like that. I think this is more likely the case as I don't see `execinfo` in Cygwin anytime soon but either way the test is conditional so it will always just fall back to disabling stacktraces if it is working in a unix like way.

The `.so`/`.dll` thing is just a quirk of unix type programming on Windows. Unless you need to use the dynamic library for any reason I would just link to the static library (the `.a` file) as I think that is easier.

Thanks for the detailed report. Glad you like the library and new website :+1: 

- Dan

**Comment by polyglotCipher** [comment]
**This patch compiles perfectly.**

One just has to keep in mind that they have to pass the `-DCELLO_NSTRACE` to `gcc` when compiling their own application and they're good to go.

Good work on the patch.

**Comment by orangeduck** [comment]
Great thanks for the help.
