### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by VanushVaswani** [orangeduck/Cello#89]
What is the status of ARM support?
Can we compile out OS, concurrency stuff and use the rest?

**Comment by radare** [comment]
That's up to the compiler, not cello

**Comment by orangeduck** [comment]
Yes that should be possible. At the moment the only OS specific stuff is threads. If whatever ARM platform/OS supports pthreads you can easily use those, otherwise I was considering making a compile option to compile a single threaded version which could be used for non POSIX platforms.

Do you have a specific application in mind or is this just a general question?

**Comment by zumpchke** [comment]
Would like to use this on microcontrollers.

**Comment by orangeduck** [comment]
I've pushed up a little patch 3ab2d4940cc4d1932d5f5ed83a39dfb3bab7fda1 you can try. Cello should now compile on non-unix and non-windows environments. Obviously the threading stuff wont work so if you try to create and run a new thread it will throw an exception but other than that everything should work fine. Tell me if you have any problems.
